// ignore_for_file: argument_type_not_assignable, list_element_type_not_assignable
import 'package:flutter/material.dart';
import 'package:rfw_gen/rfw_gen.dart';
import '../widgets/code_block.dart';
import '../widgets/doc_table.dart';
import '../widgets/link_text.dart';

@RfwWidget('root')
Widget buildApiReference() {
  return SingleChildScrollView(
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Header
        Container(
          padding: const EdgeInsets.all(32.0),
          decoration: const BoxDecoration(
            color: Color(0xFFF1F8FF),
            borderRadius: BorderRadius.all(Radius.circular(16.0)),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('API Reference',
                  style: const TextStyle(
                      fontSize: 28.0,
                      fontWeight: FontWeight.w800,
                      color: Color(0xFF141618))),
              SizedBox(height: 8.0),
              Text('Core classes, builder outputs, and runtime APIs.',
                  style: const TextStyle(
                      fontSize: 16.0, color: Color(0xFF49515A))),
            ],
          ),
        ),
        SizedBox(height: 32.0),

        // Core Classes
        Text('Core Classes',
            style: const TextStyle(
                fontSize: 22.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 8.0),
        Text('Annotation, converter, and registry from the rfw_gen package.',
            style:
                const TextStyle(fontSize: 14.0, color: Color(0xFF49515A))),
        SizedBox(height: 12.0),
        DocTable(
          headers: ['Class', 'Package', 'Description'],
          rows: [
            ['@RfwWidget', 'rfw_gen', 'Annotation for top-level widget builder functions'],
            ['RfwConverter', 'rfw_gen', 'Converts Flutter widget trees to rfwtxt strings'],
            ['WidgetRegistry', 'rfw_gen', 'Maps Flutter widget types to RFW equivalents'],
          ],
        ),
        SizedBox(height: 24.0),

        // @RfwWidget usage
        Text('@RfwWidget Annotation',
            style: const TextStyle(
                fontSize: 20.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 8.0),
        Text('Place on a top-level function with block body and return statement. The argument is the widget name in rfwtxt output.',
            style:
                const TextStyle(fontSize: 14.0, color: Color(0xFF49515A))),
        SizedBox(height: 12.0),
        CodeBlock(code: "@RfwWidget('myWidget')\\nWidget buildMyWidget() {\\n  return Text('Hello');\\n}"),
        SizedBox(height: 32.0),

        // Builder Outputs
        Text('Builder Outputs',
            style: const TextStyle(
                fontSize: 22.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 8.0),
        Text('Files generated by rfw_gen_builder when you run build_runner.',
            style:
                const TextStyle(fontSize: 14.0, color: Color(0xFF49515A))),
        SizedBox(height: 12.0),
        DocTable(
          headers: ['Output File', 'Format', 'Description'],
          rows: [
            ['.rfwtxt', 'Text', 'Human-readable RFW widget declarations'],
            ['.rfw', 'Binary', 'Compiled binary blob for runtime loading'],
            ['.rfw_library.dart', 'Dart', 'Generated library with encoded blob constant'],
            ['.rfw_meta.json', 'JSON', 'Metadata about generated widgets and imports'],
          ],
        ),
        SizedBox(height: 24.0),

        // Build command
        Text('Running the Builder',
            style: const TextStyle(
                fontSize: 20.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 12.0),
        CodeBlock(code: 'dart run build_runner build --delete-conflicting-outputs'),
        SizedBox(height: 32.0),

        // Runtime APIs
        Text('Runtime APIs',
            style: const TextStyle(
                fontSize: 22.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 8.0),
        Text('Classes and functions used at runtime to load and render RFW widgets.',
            style:
                const TextStyle(fontSize: 14.0, color: Color(0xFF49515A))),
        SizedBox(height: 12.0),
        DocTable(
          headers: ['API', 'Package', 'Description'],
          rows: [
            ['parseLibraryFile()', 'rfw', 'Parses rfwtxt string into a WidgetLibrary'],
            ['encodeLibraryBlob()', 'rfw', 'Encodes a WidgetLibrary into binary format'],
            ['decodeLibraryBlob()', 'rfw', 'Decodes binary blob back to a WidgetLibrary'],
            ['Runtime', 'rfw', 'Manages widget libraries and data bindings'],
            ['DynamicContent', 'rfw', 'Provides reactive data to remote widgets'],
            ['RemoteWidget', 'rfw', 'Flutter widget that renders a remote widget tree'],
          ],
        ),
        SizedBox(height: 24.0),

        // Runtime usage
        Text('Runtime Usage',
            style: const TextStyle(
                fontSize: 20.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 8.0),
        Text('Create a Runtime, import widget libraries, bind data with DynamicContent, then render with RemoteWidget.',
            style:
                const TextStyle(fontSize: 14.0, color: Color(0xFF49515A))),
        SizedBox(height: 12.0),
        CodeBlock(code: 'final runtime = Runtime();\\nruntime.update(\\n  const LibraryName(<String>["core", "widgets"]),\\n  createCoreWidgets,\\n);'),
        SizedBox(height: 8.0),
        CodeBlock(code: 'final data = DynamicContent();\\ndata.update("user", <String, Object>{\\n  "name": "Alice",\\n});'),
        SizedBox(height: 8.0),
        CodeBlock(code: 'RemoteWidget(\\n  runtime: runtime,\\n  data: data,\\n  widget: const FullyQualifiedWidgetName(\\n    LibraryName(<String>["main"]),\\n    "root",\\n  ),\\n)'),
        SizedBox(height: 32.0),

        // Type Encoding Quick Reference
        Text('Type Encoding Quick Reference',
            style: const TextStyle(
                fontSize: 22.0,
                fontWeight: FontWeight.bold,
                color: Color(0xFF141618))),
        SizedBox(height: 8.0),
        Text('How Flutter types are encoded in rfwtxt format.',
            style:
                const TextStyle(fontSize: 14.0, color: Color(0xFF49515A))),
        SizedBox(height: 12.0),
        DocTable(
          headers: ['Flutter Type', 'rfwtxt Encoding', 'Example'],
          rows: [
            ['Color', '0xAARRGGBB integer', '0xFF000000'],
            ['EdgeInsets', 'List of 1-4 doubles', '[16.0, 8.0]'],
            ['TextStyle', 'Map with style properties', '{ fontSize: 24.0, fontWeight: "bold" }'],
            ['Alignment', 'Map with x, y', '{ x: 0.0, y: -1.0 }'],
            ['BoxDecoration', 'Map with type: "box"', '{ type: "box", color: 0xFF000000 }'],
            ['BorderRadius', 'List of radius maps', '[{ x: 8.0 }]'],
            ['Duration', 'Integer (milliseconds)', '300'],
            ['Curve', 'String name', '"easeInOut"'],
          ],
        ),
        SizedBox(height: 32.0),

        // Navigation
        LinkText(text: 'Widget Gallery', page: 'widget-gallery'),
        SizedBox(height: 8.0),
        LinkText(text: 'Syntax Guide', page: 'syntax-guide'),
      ],
    ),
  );
}
