name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies (rfw_gen)
        working-directory: packages/rfw_gen
        run: flutter pub get
      - name: Analyze rfw_gen
        run: dart analyze packages/rfw_gen
      - name: Format rfw_gen
        run: dart format --set-exit-if-changed packages/rfw_gen
      - name: Test rfw_gen
        working-directory: packages/rfw_gen
        run: dart test

      - name: Get dependencies (rfw_gen_builder)
        working-directory: packages/rfw_gen_builder
        run: flutter pub get
      - name: Analyze rfw_gen_builder
        run: dart analyze packages/rfw_gen_builder
      - name: Format rfw_gen_builder
        run: dart format --set-exit-if-changed packages/rfw_gen_builder
      - name: Test rfw_gen_builder
        working-directory: packages/rfw_gen_builder
        run: dart test
