name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap

      - name: Analyze rfw_gen
        run: dart analyze packages/rfw_gen
      - name: Format rfw_gen
        run: dart format --set-exit-if-changed packages/rfw_gen
      - name: Test rfw_gen
        working-directory: packages/rfw_gen
        run: dart test

      - name: Analyze rfw_gen_builder
        run: dart analyze packages/rfw_gen_builder
      - name: Format rfw_gen_builder
        run: dart format --set-exit-if-changed packages/rfw_gen_builder
      - name: Test rfw_gen_builder
        working-directory: packages/rfw_gen_builder
        run: dart test
